# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'psr_api_plugin_Example' do
  pod 'psr_api_plugin', :path => '../'
  
#  pod 'TextFieldEffects'
  pod 'Alamofire', '~> 4.8.2'
   
  pod 'SwiftyJSON'
#  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
#  pod 'MaterialComponents/TextControls+OutlinedTextFields'
#  pod 'SKCountryPicker'
  pod 'EzPopup'
#  pod 'EasyTipView', '~> 2.0.4'

  target 'psr_api_plugin_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    
    
  end
end
